name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Enable Corepack
      run: corepack enable
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run TypeScript check and build
      run: pnpm run build
      
    - name: Run linting
      run: pnpm run lint